language:
  - php

php:
  - 5.4

install:
  - composer --prefer-source install

before_script:  
  - git clone -q https://github.com/phalcon/cphalcon.git
  - ./cphalcon/unit-tests/ci/install_prereqs.sh
  - sudo apt-get -qq install php5-dev
  - (cd cphalcon/build; sudo ./travis-install && phpenv config-add ../../config/php.d/phalcon.ini)

script: (cd tests; phpunit --debug)
